import payload from "./scenarios.json";
import type { DemoPayload, ScenarioPresentation } from "./types.js";
import {
  comparisonHtml,
  headerHtml,
  highlightClass,
  stepCardHtml,
  tabsHtml,
  trackHtml,
} from "./render.js";

// The fixture is generated by `just export-demo`; this file only draws it.
const scenarios = (payload as DemoPayload).scenarios;

let activeScenario = 0;
let activeStep = 0;
let playing = false;
let playTimer: number | undefined;

const comparisonEl = document.getElementById("comparison")!;
const tabsEl = document.getElementById("tabs")!;
const headerEl = document.getElementById("scenario-header")!;
const trackEl = document.getElementById("step-track")!;
const cardEl = document.getElementById("step-card")!;
const prevBtn = document.getElementById("prev-btn") as HTMLButtonElement;
const nextBtn = document.getElementById("next-btn") as HTMLButtonElement;
const playBtn = document.getElementById("play-btn") as HTMLButtonElement;

function renderComparison() {
  comparisonEl.innerHTML = comparisonHtml(scenarios, activeScenario);

  comparisonEl.querySelectorAll(".comp-card").forEach((el) => {
    el.addEventListener("click", () => {
      selectScenario(Number((el as HTMLElement).dataset.index));
    });
  });
}

function renderTabs() {
  tabsEl.innerHTML = tabsHtml(scenarios, activeScenario);

  tabsEl.querySelectorAll(".tab").forEach((el) => {
    el.addEventListener("click", () => {
      selectScenario(Number((el as HTMLElement).dataset.index));
    });
  });
}

function renderHeader(scenario: ScenarioPresentation) {
  headerEl.innerHTML = headerHtml(scenario);
}

function renderTrack(scenario: ScenarioPresentation) {
  trackEl.innerHTML = trackHtml(scenario.steps, activeStep);

  trackEl.querySelectorAll(".step-dot").forEach((el) => {
    el.addEventListener("click", () => {
      stopPlay();
      activeStep = Number((el as HTMLElement).dataset.index);
      render();
    });
  });
}

function renderStep(scenario: ScenarioPresentation) {
  const step = scenario.steps[activeStep];
  cardEl.className = `step-card ${highlightClass(step)}`;
  cardEl.innerHTML = stepCardHtml(step);
}

function updateControls(scenario: ScenarioPresentation) {
  prevBtn.disabled = activeStep === 0;
  nextBtn.disabled = activeStep >= scenario.steps.length - 1;
  playBtn.textContent = playing ? "Pause" : "Play scenario";
}

function render() {
  const scenario = scenarios[activeScenario];
  renderComparison();
  renderTabs();
  renderHeader(scenario);
  renderTrack(scenario);
  renderStep(scenario);
  updateControls(scenario);
}

function selectScenario(index: number) {
  stopPlay();
  activeScenario = index;
  activeStep = 0;
  render();
}

function stopPlay() {
  playing = false;
  if (playTimer !== undefined) {
    window.clearInterval(playTimer);
    playTimer = undefined;
  }
}

function togglePlay() {
  if (playing) {
    stopPlay();
    render();
    return;
  }

  playing = true;
  playTimer = window.setInterval(() => {
    const scenario = scenarios[activeScenario];
    if (activeStep >= scenario.steps.length - 1) {
      stopPlay();
      render();
      return;
    }
    activeStep += 1;
    render();
  }, 1400);
  render();
}

prevBtn.addEventListener("click", () => {
  stopPlay();
  if (activeStep > 0) activeStep -= 1;
  render();
});

nextBtn.addEventListener("click", () => {
  stopPlay();
  const scenario = scenarios[activeScenario];
  if (activeStep < scenario.steps.length - 1) activeStep += 1;
  render();
});

playBtn.addEventListener("click", togglePlay);

render();
