/**
 * Shape of `scenarios.json`, which is generated by the Python lab.
 *
 * These are presentation types only. The browser demo never decides whether a
 * call is allowed or blocked — it renders decisions the Python executors
 * already made. Regenerate the fixture with `just export-demo`.
 */

export type Highlight = "danger" | "safe" | "neutral";
export type OutcomeKind = "leaked" | "safe" | "neutral";

export interface DemoStep {
  id: string;
  title: string;
  body: string;
  actor: string | null;
  code: string | null;
  highlight: Highlight;
}

export interface ScenarioPresentation {
  number: number;
  title: string;
  label: string;
  comparison_label: string;
  subtitle: string;
  policy: string;
  outcome: string;
  outcome_kind: OutcomeKind;
  steps: DemoStep[];
}

export interface DemoPayload {
  generated_by: string;
  scenarios: ScenarioPresentation[];
}
